<div class="hb-rating-slider">
	<div id="popup"  class="showpopup" style="display: none;">
<div class="signup-bg">
		<div class="form-box">
					<form method="POST" action="https://www.psydro.com/signup" accept-charset="UTF-8" id="normal_user_signup" class="form-horizontal" enctype="multipart/form-data" novalidate="novalidate"><input name="_token" type="hidden" value="5FecGdkljPuFYVxBr8mh36TuFi213XtQwujWvc1P">
					<div class="avatar-img">
						<figure>
							
							<div class="circle-profile-image" id="user-profile-image-result" style="background: url(https://www.psydro.com/frontend_assets/images/avatar.jpg);"></div>
						</figure>
						<div class="upload">
							<label for="upload-img">
								<i id="user-profile-image" name="profile_image" data-attr-id="profile_image" class="zmdi zmdi-upload"></i>
							</label>
						</div>
					</div>
					<h2>Sign up</h2>
						<fieldset>
							<label>Username
							 <input class="form-control col-md-7 col-xs-12" placeholder="Username" required="" id="username" name="username" type="text" value="" aria-required="true">
						</label></fieldset>
						<fieldset>
							<label>First name</label>
							<!-- <input type="text"   name="first_name" id="first_name"/> -->
							<input class="form-control col-md-7 col-xs-12" placeholder="First Name" required="" id="first_name" name="first_name" type="text" value="" aria-required="true">
						</fieldset>
						<fieldset>
							<label>Last name</label>
							
							<input class="form-control col-md-7 col-xs-12" placeholder="Last Name" required="" id="last_name" name="last_name" type="text" value="" aria-required="true">
						</fieldset>
						<fieldset>
							<label>Email</label>
							<!-- <input type="email"   name="email" id="email"/> -->
							<input class="form-control col-md-7 col-xs-12" placeholder="email@domain.com" required="" id="email" name="email" type="email" value="" aria-required="true">
						</fieldset>
						<fieldset>
							<label>Password</label>
							<input type="password" name="password" id="password" value="">
							
						</fieldset>
						<fieldset>
							<label>Confirm Password</label>
							<input type="password" name="confirm_password" id="confirm_password" value="">
						
						</fieldset>
						<fieldset>
							<label>Age</label>
							<select name="age" id="age">
								<option value="">Select</option>
								<option value="Under 18">Under 18</option>
								<option value="19-35">19-35</option>
								<option value="36-60">36-60</option>
								<option value="Above 60">Above 60</option>
							</select>
						</fieldset>
						<fieldset>
							<label>Gender</label>
							<select name="gender" id="gender">
								<option value="">Select</option>
								<option value="1">Male</option>
								<option value="0">Female</option>
								<option value="2">Other</option>
							</select>
						</fieldset>

						<fieldset>
							<label>Location</label>
							
							  <input class="form-control col-md-7 col-xs-12" placeholder="Location" required="" id="autocomplete" onfocus="geolocate(&quot;autocomplete&quot;)" name="location" type="text" value="" aria-required="true" autocomplete="off">
						</fieldset>
						<fieldset>
							<label><input type="checkbox" class="regular-checkbox" name="terms" id="terms"> I agree to the <a href="https://www.psydro.com/term-service" target="__blank">Terms and Conditions</a></label>
						</fieldset>
						<fieldset>
							<input type="submit" value="Submit" name="submit">
							<input type="reset" value="Cancel">
						</fieldset>
						
					
					        </form>
					<div class="or"><p>OR</p></div>
					<div class="account-already">
						Already have account ? <a href="#login" class="fancybox hidden-xs hidden-sm">SIGN IN <i class="zmdi zmdi-arrow-right"></i></a>
						</div>
					</div>
					</div>
	</div>
		<div onclick="javascript:show_signup_form();" >Consumer :: Sign Up Form</div>
</div>
<div> :: Under Development :: </div>

<div class="hb-rating-slider">
	<div id="hb-rating-slider-signup"  class="showpopup" style="display: none;">
		<div id="popupContact">
				<img id="close" src="images/3.png" onclick ="div_hide()">
				<div class="container">
				<form action="#" method="post" id="form" name="form">
					

				    <label id ="hb-user-firstName" for="hb-user-firstName">First Name</label>
				    <input type="text" class="hb-user-firstName" id="hb-user-firstName" name="hb-user-firstName" placeholder="First Name" >
	
				    <label id ="hb-user-lastName" for="hb-user-lastName">Last Name</label>
				    <input type="text" class="hb-user-lastName" id="hb-user-lastName" name="hb-user-firstName" placeholder="Last Name" >

				    <label id ="hb-user-email" for="hb-user-email">Email</label>
				    <input type="email" class="hb-user-email" id="hb-user-email" name="hb-user-email" placeholder="Email Id" >

				   <label for="hb-pwd">Password</label>
				   <input type="pwd" id="hb-pwd" class="hb-pwd" name="hb-pwd" placeholder="**********" />
				   
				   <div class="row">
				    	<div class="col-md-6">
								<a href="#"><span>Forgtten Password?</span></a>
				    	</div>
				    	<div class="col-md-6">
				    		<!-- <a href="javascript:%20check_empty()" id="submit">Submit</a> -->
			    			<input type="submit" name="submit" />		      	    		
				    	</div>
				    </div>
					
				</form>
				</div>
		</div>

	</div>
	</div>


